### ISSUE TITLE
Input Tweaks

### ISSUE THREAD

**Issue by jared-hughes** [DesModder/DesModder#145]
This is an issue consolidating a few other issues, all of which are small tweaks to how expressions are edited:

- [x] Shift+Enter for newlines inside notes (https://github.com/DesModder/DesModder/issues/36)
- [ ] Function Iteration (https://github.com/DesModder/DesModder/issues/22)
- [ ] Multiline expressions (unlikely) (https://github.com/DesModder/DesModder/issues/75)
- [ ] Condition on a folder (https://github.com/DesModder/DesModder/issues/33)
- [ ] Ctrl+G to go to a line (https://github.com/DesModder/DesModder/issues/81)
- [ ] More greek letters (https://github.com/DesModder/DesModder/issues/35)
- [ ] Folder tools (https://github.com/DesModder/DesModder/issues/93)
