### ISSUE TITLE
Roadmap for exposing Text Mode editor

### ISSUE THREAD

**Issue by jared-hughes** [DesModder/DesModder#710]
- [ ] Clearer subpackage layout (allows treating `moo` and codemirror as npm dependencies instead of bundled in)
  - [x] Use [import/no-extraneous-dependencies](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md) from [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import/tree/main) to enforce that subpackages only use deps defined in their package.json
  - [x] ~~Use rulesdir or another import/ rule to ensure that the main package has all the dependencies, so install is a single `npm install` with no postinstall script~~ Turns out this was trivial: just needed to mark the inner packages as dependencies of the outer.
- [x] Set up the editor to allow passing in `Calc` ~~and `Desmos`~~ instead of reading from globals
  - (NAH) ~~Access dependencies from there: `DCGView`, `Tooltip`, `Keys` (currently exposed via Private)~~ (Desmos is global typically)
  - [x] Access `ExpressionView`, `ImageIconView` without needing replacements
- Expose API to create a Text Mode Editor with different levels of integration:
  - (NAH) Fully integrated: placed inside the expression list, update the Calc on change, and process onCalcEvent
    - Current DesModder experience
    - Requires replacements to be perfect in general ("## Hide the keypad when in text mode", "## Add text mode toggle button", "## Add Text Mode class for styling").
  - [x] Separate editor: placed in an external element, update the Calc on change, and process onCalcEvent
    - (NAH) Might want to trigger ?noexpressions on the Calc because we don't have handling for the user editing expressions directly.
  - Fully separate: placed in an external element, no communication with Calc
    - `Calc` and `Desmos` may be used to initialize the text mode config (optional), but otherwise ignored.
    - This is trickier than I first thought. Stuff like style circles will not work without an evaluator. Deferring.
